### ISSUE TITLE
Shared Address Object

### ISSUE THREAD

**Issue by ronsak** [chrisgoodwins/paloalto_add-addresses#2]
Hi,

This script works very well. But I am unable to make it work for shared address object creation among different vsys. Can you create one for creating share address objects in firewall?

/config/shared/address/entry

Thanks.

**Comment by danielbostock** [comment]
Hey Ronsak,

That is a good point. I haven't very often played with different vsys on a Palo (I did a lot with ASA's).

To clarify, do you want to be able to run the same script (including same CSV's) simultaneously across multiple vsys's, or would you be happy with doing one vsys at a time?

The difference is, I can loop over vsys's provided or I can allow you to manually enter a specific vsys at the start of the script.

Thanks,
Daniel.

**Comment by chrisgoodwins** [comment]
I can add support for shared address objects, that should be no problem

**Comment by ronsak** [comment]
Hi,

Thanks for the response. I was thinking of making it work to
xpath /config/shared/address/entry instead of /config/devices/entry. But
running the same script simultaneously across multiple vsys is fine for me.

Thank you so much.

**Comment by chrisgoodwins** [comment]
Hello,

I've added multi-vsys capability, along with the ability to add to the shared contexts on firewall and Panorama. I don't have a multi-vsys firewall to test this out on, so please let me know if you run into any issues, and I will address them.

Thanks

**Comment by ronsak** [comment]
Hi,

The script worked perfectly in multi-vsys environment. Thank you so much.
